from addcomment import AddComment
from deletecomment import DeleteComment
from deletepost import DeletePost
from editcomment import EditComment
from editpost import EditPost
from information import Information
from login import Login
from logout import Logout
from main import Main
from newpost import NewPost
from postpage import PostPage
from register import Register
